import hashlib
import uuid
import json
import os
import datetime
import base64
from supabase import create_client

SUPABASE_URL = "https://aeeliekwqlruiacxeluv.supabase.co"
SUPABASE_KEY = "sb_publishable_lpWnp-XzPJdjnqwmCLt2fA_cT7FcxCb"
CACHE_FILE = "license_cache.dat" # Using .dat to hide plain JSON nature

# This secret salt ensures the cache signature cannot be re-generated by a user
SECRET_SALT = "pharmacisco_pro_secure_v1_8x!@" 

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

def get_machine_id():
    mac = uuid.getnode()
    return hashlib.sha256(str(mac).encode()).hexdigest()

def _sign_data(data_dict):
    """Mixes the dictionary content with a secret salt to create a tamper-proof seal."""
    raw = json.dumps(data_dict, sort_keys=True)
    return hashlib.sha256((raw + SECRET_SALT).encode()).hexdigest()

def save_cache(data):
    """Seals the data with a signature and encodes it in Base64."""
    data["signature"] = _sign_data({k: v for k, v in data.items() if k != "signature"})
    raw_str = json.dumps(data)
    encoded = base64.b64encode(raw_str.encode()).decode()
    with open(CACHE_FILE, "w") as f:
        f.write(encoded)

def load_cache():
    if not os.path.exists(CACHE_FILE):
        return None
    try:
        with open(CACHE_FILE, "r") as f:
            encoded = f.read()
            raw_str = base64.b64decode(encoded).decode()
            data = json.loads(raw_str)
            
            # Verify Signature (Has anyone tampered with the file?)
            saved_signature = data.pop("signature", None)
            if saved_signature != _sign_data(data):
                return None # Tampered file detected!
            
            return data
    except Exception:
        return None

def verify_online(license_key, machine_id):
    response = supabase.rpc(
        "verify_license",
        {
            "input_license": license_key,
            "input_machine": machine_id
        }
    ).execute()
    return response.data

def verify_license(license_key):
    machine_id = get_machine_id()
    today = datetime.date.today()

    try:
        # Online Verification attempt
        result = verify_online(license_key, machine_id)

        if result and result.get("valid"):
            cache = {
                "license_key": license_key,
                "machine_id": machine_id,
                "last_verified": str(today),
                "expiry_date": result["expiry_date"]
            }
            save_cache(cache)
            return True
        return False

    except Exception:
        # Offline Mode fallback
        cache = load_cache()
        if not cache:
            return False

        last = datetime.date.fromisoformat(cache["last_verified"])
        
        # 1. Anti Time-travel check (if today is before last verified, user rolled back their clock)
        if today < last:
            return False

        # 2. 7-day offline check
        delta = (today - last).days
        if delta <= 7:
            # Expiry date check
            expiry = datetime.date.fromisoformat(cache["expiry_date"])
            if today <= expiry:
                return True

        return False